### ISSUE TITLE
norm of vector with uncertainties

### ISSUE THREAD

**Issue by karlwessel** [lebigot/uncertainties#121]
Calculating the norm of a numpy array with uncertainties using numpy.linalg.norm throws an error which can be reproduced with the following MWE:
```
from uncertainties import unumpy
import numpy
a = unumpy.uarray([1, 1], [1, 1])
numpy.linalg.norm(unumpy.nominal_values(a)) # works fine
numpy.linalg.norm(a)
```
This throws the following exception:
```
AttributeError: 'AffineScalarFunc' object has no attribute 'sqrt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in norm
  File "lib/python3.6/site-packages/numpy/linalg/linalg.py", line 2483, in norm
    ret = sqrt(sqnorm)
TypeError: loop of ufunc does not support argument 0 of type AffineScalarFunc which has no callable sqrt method
```

This is with uncertainties version 3.1.2 and numpy version 1.17.4.

**Comment by lebigot** [comment]
Thanks for reporting this. Either we should have a unumpy.linalg.norm function or, better, some mechanism that makes the original numpy.linalg.norm work.

**Comment by karlwessel** [comment]
I added a pull request that fixes the problem. However, since it adds sqrt as a member function to AffineScalarFunc it might introduce some unexpected side effects.

**Comment by lebigot** [comment]
Thanks. I am quite confident that this should work fine. I'll have to review the pull request when I am close to my personal computer but so far things look good.

**Comment by lebigot** [comment]
Thanks. I am quite confident that this should work fine. I'll have to review the pull request when I am close to my personal computer but so far things look good.
