### ISSUE TITLE
Test failure under Python 3.9

### ISSUE THREAD

**Issue by felixonmars** [lebigot/uncertainties#131]
It looks rather strange to me:

```
======================================================================
FAIL: Failure: AssertionError (filter ('', PendingDeprecationWarning) did not catch any warning)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.9/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.9/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.9/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/build/python-uncertainties/src/uncertainties-3.1.4/uncertainties/lib1to2/test_1to2.py", line 40, in <module>
    import test.test_lib2to3.support as support
  File "/usr/lib/python3.9/test/test_lib2to3.py", line 5, in <module>
    from lib2to3.tests import load_tests
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/usr/lib/python3.9/test/support/__init__.py", line 1171, in _filterwarnings
    raise AssertionError("filter (%r, %s) did not catch any warning" %
AssertionError: filter ('', PendingDeprecationWarning) did not catch any warning

----------------------------------------------------------------------
Ran 52 tests in 1.713s

FAILED (failures=1)
```

**Comment by felixonmars** [comment]
Turns out it's only present when invoking with `python setup.py nosetests`, not `nosetests` directly.

**Comment by lebigot** [comment]
Well spotted. Does calling `nosetests` directly solve your problem, then?

I'm not clear about whether `python setup.py nosetests` is supposed to work (I didn't do anything so that it does, but maybe that's enough?).

**Comment by felixonmars** [comment]
Calling `nosetests` directly solves the problem. It is enough for my Arch packaging :)

**Comment by lebigot** [comment]
Thanks for the feedback!
