### ISSUE TITLE
OverflowError with unumpy.exp

### ISSUE THREAD

**Issue by noonuu** [lebigot/uncertainties#134]
I was working with the blackbody function
```
f(E) = (A*pow(E, 3))/(exp(E/kT) - 1)
```
Where `E` is the energy range over which I need this function to be evaluated, `kT` is the temperature parameter, `A` is the amplitude of the model. However, with the uncertainties package, it doesn't work.
```python
import numpy as np
import uncertainties as uties
import uncertainties.unumpy as unp


x, j, b =[], np.log10(8.), np.log10(100e6)

while j<=b:
    data=10**j
    x.append(data)
    j=j+0.01
energy = np.array(x)


def blackbody_model(energy, **bb_parameters):
    try:
        amplitude_bb = uties.ufloat(bb_parameters['amp_bb'][0], bb_parameters['amp_bb'][1])
        kT_bb = uties.ufloat(bb_parameters['kT_bb'][0], bb_parameters['kT_bb'][1])
    except KeyError:
        amplitude_bb = uties.ufloat(bb_parameters['amp_bb_eac'][0], bb_parameters['amp_bb_eac'][1])
        kT_bb = uties.ufloat(bb_parameters['kT_bb_eac'][0], bb_parameters['kT_bb_eac'][1])
    
    f1 = unp.exp(energy/kT_bb) - 1
    f2 = pow(energy, 3)/f1
    f3 = amplitude_bb*f2
    
    return f3

bb_parameters = {'amp_bb': [1.7723887e-06, 1.1836137e-06], 'kT_bb': [67.121216, 13.658229]}
bb_model = blackbody_model(energy, **bb_parameters)
```

The statment `f1` produces error, which I will be including in the second comment. What I did to try and resolve this issue was to let `f1` be a list and see where it goes

```python
f1 = []
try:
    for i in energy:
        f1.append(unp.exp(i/kT_bb) - 1)
except OverflowError:
    print i
```
However, it still produces error and when I print `f1` on console, it gives me an `OverflowError: (34, 'Numerical result out of range')` and to obtain results I have to do `f1[0:-31]` which gives me about 347 length out of 710 for the energy input. However, if I do this without using uncertainties package (i.e, with `sympy` or without error values) it does give me error but it executes it and it returns the `bb_model` that I can plot against the `energy` parameter.

**Comment by noonuu** [comment]
This is the error traceback that I receive while running the above code

```
Traceback (most recent call last):

  File "<ipython-input-40-d2ed1c304be2>", line 1, in <module>
    runfile('/home/syeda/Desktop/thesis_ist/all_codes_cleanup/0000__good_and_best_criteria_codes_for_juniors/test', wdir='/home/syeda/Desktop/thesis_ist/all_codes_cleanup/0000__good_and_best_criteria_codes_for_juniors')

  File "/home/syeda/miniconda2/envs/fermi/lib/python2.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/syeda/miniconda2/envs/fermi/lib/python2.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 102, in execfile
    builtins.execfile(filename, *where)

  File "/home/syeda/Desktop/thesis_ist/all_codes_cleanup/0000__good_and_best_criteria_codes_for_juniors/test", line 38, in <module>
    bb_model = blackbody_model(energy, **bb_parameters)

  File "/home/syeda/Desktop/thesis_ist/all_codes_cleanup/0000__good_and_best_criteria_codes_for_juniors/test", line 31, in blackbody_model
    f1 = unp.exp(energy/kT_bb) - 1

  File "/home/syeda/miniconda2/envs/fermi/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)

  File "/home/syeda/miniconda2/envs/fermi/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2167, in _vectorize_call
    outputs = ufunc(*inputs)

  File "/home/syeda/miniconda2/envs/fermi/lib/python2.7/site-packages/uncertainties/core.py", line 705, in f_with_affine_output
    f_nominal_value = f(*args_values, **kwargs)

OverflowError: math range error
```

**Comment by lebigot** [comment]
I cannot say for sure because I don't have a computer with me right now and the code above takes a long time to parse (it looks like C code!), but my hunch is that evaluating the uncertainty is what itself gives an overflow (as you don't observe the same problem without uncertainties). 

This is quite possible, as the derivative of exp(E/kT) with respect to kT, which is needed for calculating the uncertainty, is numerically much bigger than exp(E/kT) itself, with your values. This is pretty normal and it's hard to do anything against in `uncertainties` given the general nature of the code. 

Now, it would make sense that calculations done without uncertainties and those done with uncertainties produce a similar behavior (except for the fact that uncertainty calculations require more computations and therefore might raise additional numerical errors). Can you share what this "no uncertainty" case gives (code and error message)?

**Comment by noonuu** [comment]
Hey, thanks for getting back. I'm attaching the code and error for when I use it without the uncertainty/error included
```python
import numpy as np

x, j, b =[], np.log10(8.), np.log10(100e6)

while j<=b:
    data=10**j
    x.append(data)
    j=j+0.01
energy = np.array(x)


def blackbody_model(energy, **bb_parameters):
    try:
        amplitude_bb = bb_parameters['amp_bb'][0]
        kT_bb = bb_parameters['kT_bb'][0]
    except KeyError:
        amplitude_bb = bb_parameters['amp_bb_eac'][0]
        kT_bb = bb_parameters['kT_bb_eac'][0]

    f1 = np.exp(energy/kT_bb) - 1
    f2 = pow(energy, 3)/f1
    f3 = amplitude_bb*f2

    return f3


bb_parameters = {'amp_bb': [1.7723887e-06, 1.1836137e-06], 'kT_bb': [67.121216, 13.658229]}
bb_model = blackbody_model(energy, **bb_parameters)
```
And it gives me
```
runfile('/home/syeda/Desktop/thesis_ist/all_codes_cleanup/0000__good_and_best_criteria_codes_for_juniors/test.py', wdir='/home/syeda/Desktop/thesis_ist/all_codes_cleanup/0000__good_and_best_criteria_codes_for_juniors')
/home/syeda/Desktop/thesis_ist/all_codes_cleanup/0000__good_and_best_criteria_codes_for_juniors/test.py:29:
RuntimeWarning: overflow encountered in exp
  f1 = np.exp(energy/kT_bb) - 1
```
It gives me 378 values and the rest it automatically appends 0 at the end when I check the bb_model output

**Comment by lebigot** [comment]
Thanks. I am again of the opinion that uncertainties should give the same kind of behavior as NumPy, so as to not surprise users: I'll have a look. Thanks for reporting.

**Comment by noonuu** [comment]
An off-topic question, though. I am working with four other models like the one I just showed you and none of them is simple to write in a single line. All these models are additional models, will the uncertainty package work correctly since I'm not evaluating them in a single "statement".
```
first_model = some_expression

second_model = some_other_expression
second_model = second_model*some_more_expression

final_model = first_model + second_model
```

**Comment by lebigot** [comment]
This is fully handled by uncertainties.
