### ISSUE TITLE
ImportError: No module named 'lib2to3.tests' -- while running tests

### ISSUE THREAD

**Issue by pwaller** [lebigot/uncertainties#34]
```
$ python3 -V
Python 3.4.3+
$ nosetests3 --version
nosetests3 version 1.3.6
$ nosetests3 uncertainties
$ python3 -c 'import lib2to3.tests'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'lib2to3.tests'
$ nosetests3 uncertainties
E.........../home/pwaller/.local/src/uncertainties/build/lib/uncertainties/unumpy/test_unumpy.py:318: UserWarning: Obsolete: uarray() should now be called with two arguments. Code can be automatically updated with python -m uncertainties.1to2 -w ProgramDirectory.
  arr_obs = unumpy.uarray.__call__(([1, 2], [1, 4]))  # Obsolete call
[ lots of warnings about obsolete stuff ]
======================================================================
ERROR: Failure: ImportError (No module named 'lib2to3.tests')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pwaller/.local/src/uncertainties/build/lib/uncertainties/lib1to2/test_1to2.py", line 39, in <module>
    import test.test_lib2to3.support as support
ImportError: No module named 'test.test_lib2to3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/pwaller/.local/src/uncertainties/build/lib/uncertainties/lib1to2/test_1to2.py", line 42, in <module>
    import lib2to3.tests.support as support
ImportError: No module named 'lib2to3.tests'

----------------------------------------------------------------------
Ran 52 tests in 2.964s

FAILED (errors=1)
```

**Comment by pwaller** [comment]
I also get this error if I try to run the tests in the uncertainties directory:

```
~/.local/src/uncertainties$ nosetests3
E
======================================================================
ERROR: Failure: AttributeError ('dict' object has no attribute 'iteritems')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/pwaller/.local/src/uncertainties/uncertainties/__init__.py", line 2609, in <module>
    ops_with_reflection = get_ops_with_reflection()
  File "/home/pwaller/.local/src/uncertainties/uncertainties/__init__.py", line 2563, in get_ops_with_reflection
    for (op, derivatives) in derivatives_list.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

----------------------------------------------------------------------
Ran 1 test in 0.037s

FAILED (errors=1)
```

**Comment by lebigot** [comment]
In order to get a version that works with Python3, you need to run `2to3 -w .` on the code (see [the installation documentation](http://pythonhosted.org/uncertainties/#manual-download-and-install). Did you do this?

**Comment by pwaller** [comment]
OK, I've done that now. I no longer get `no attribute 'iteritems'`, but I still get `ImportError: No module named 'lib2to3.tests'`.

Also, [INSTALL.txt](https://github.com/lebigot/uncertainties/blob/a3ab1af942debc073bab2ace06105232b967e145/INSTALL.txt) doesn't mention it.

**Comment by lebigot** [comment]
Good point, about INSTALL.txt. I fixed it in revision 027a0a27da75a55e1730f16a3f7705b6b919929d.

I can't reproduce the error that you are seeing, when I run nosetests with Python 3.5. I am not sure how to run MacPort's nosetests for Python 3.5 with Python 3.4, so I have not run the tests through Python 3.4, but I nonetheless get no error when doing, inside Python 3.4, an `import lib2to3.tests`. Can you try this?

If this fails, what distribution of Python are you using?

**Comment by pwaller** [comment]
```
$ python3
Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lib2to3.tests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'lib2to3.tests'
>>> 
```

I'm running on Ubuntu 15.10.

I can reproduce it with this docker command:

```
$ docker run --rm ubuntu:15.10 bash -c 'apt-get update && apt-get install -y python3 && python3 -c "import lib2to3.tests"'
<snip>
Processing triggers for systemd (225-1ubuntu9) ...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'lib2to3.tests'
```

**Comment by lebigot** [comment]
It looks like while [lib2to3](https://docs.python.org/2/library/2to3.html#module-lib2to3) is part of the standard library, it is not installed with the `python3` package. This is a little strange, given the fact that some Ubuntu Python 3 packages [do install it](http://packages.ubuntu.com/precise-updates/i386/python3.2/filelist). I would suggest that you find where/whether this standard module is provided by one of the Ubuntu packages.

**Comment by pwaller** [comment]
Bah, I don't find any matches :(
```
$ apt-cache search 2to3
```

And it doesn't seem to be shipped in any package that I can find [in my distribution](http://packages.ubuntu.com/search?searchon=contents&keywords=2to3&mode=exactfilename&suite=wily&arch=amd64) (wily).

**Comment by lebigot** [comment]
This is because 2to3 is not in a file name, I think. I understand that [you have the standard lib2to3](http://packages.ubuntu.com/search?mode=exactfilename&suite=wily&section=all&arch=amd64&keywords=pytree.py&searchon=contents) in package libpython3.4-stdlib. Can you install and try again?

**Comment by pwaller** [comment]
Yep, lib2to3 exists, but not lib2to3.tests. I guess the packagers figured it wasn't necessary to distribute them?

If you search this list for `lib2to3`, you can see: http://packages.ubuntu.com/wily/amd64/libpython3.4-stdlib/filelist

I guess this is a debian/ubuntu issue? Is there any way we can fix it here without having to get them to fix their packaging?

**Comment by pwaller** [comment]
Yeah, it appears they do something with them [here as far as I can tell](http://bazaar.launchpad.net/~doko/python/pkg3.4-debian/view/head:/rules#L975).

**Comment by lebigot** [comment]
If you don't insist on testing everything, you can simply remove `uncertainties/lib1to2/test_1to2.py`. What do you think?

**Comment by pwaller** [comment]
Seems fair enough to me. Feels like a debian bug I guess, if it's a valid thing to depend on this code. Thanks for helping.
